const {chromium}=require('C:/Users/咖波/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});
 const page=await browser.newPage({viewport:{width:1366,height:768}});const failures=[];
 await page.goto('http://127.0.0.1:8766');await page.locator('#password').fill('qa-local-testing-only');await page.locator('#auth-form button').click();await page.locator('.stats').waitFor();
 await page.locator('[data-nav="catalog"]').click();await page.locator('.catalog-card').first().waitFor();
 const all=await (await page.request.get('http://127.0.0.1:8766/api/products?status=uncounted')).json();
 const uncounted=all.items[0];
 if(!uncounted)throw Error('QA fixture needs an uncounted catalog item');
 await page.locator('#search').fill(uncounted.name);await page.waitForTimeout(600);
 const card=page.locator('.catalog-card').filter({has:page.locator('h3',{hasText:uncounted.name})}).first();
 if(!(await card.innerText()).includes('未盤點'))failures.push('Catalog hides unknown stock');
 await page.evaluate(()=>{window.print=()=>{};});await page.locator('[data-action="print"]').click();await page.locator('.print-page').waitFor({state:'attached'});
 const printed=page.locator('.print-card').filter({has:page.locator('h3',{hasText:uncounted.name})}).first();
 if(!(await printed.textContent()).includes('未盤點'))failures.push('Print hides unknown stock');
 await page.route('**/api/meta',async route=>{const response=await route.fetch();const body=await response.json();body.export.pending=true;body.export.last_export={created_at:'2026-10-01T09:00:00+08:00'};await route.fulfill({response,json:body});});
 await page.reload();await page.locator('.stats').waitFor();await page.locator('[data-nav="history"]').click();
 await page.waitForTimeout(250);
 if(await page.locator('#history-product').count()!==1)failures.push('History lacks product filter');
 if(!(await page.locator('#main').innerText()).includes('需重新匯出'))failures.push('Export pending status hidden');
 await page.route('**/api/invoice-exports',route=>route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:{message:'請先處理發票商品的待確認資料',fields:{issues:['缺價測試商品：尚未設定售價']}}})}));
 await page.locator('[data-action="invoice-export"]').click();await page.waitForTimeout(250);
 if(!(await page.locator('body').innerText()).includes('缺價測試商品'))failures.push('Export failure hides item details');
 if(await page.locator('#dialog').evaluate(d=>d.open))await page.locator('#dialog-close').click();
 await page.locator('[data-nav="dashboard"]').click();await page.getByRole('button',{name:'資料管理',exact:true}).first().click();await page.locator('#begin-import').click();await page.locator('#import-form').waitFor({timeout:60000});
 if(!(await page.locator('#dialog-body').innerText()).includes('81 筆未盤點'))failures.push('Import preview hides missing values summary');
 if(await page.locator('[name="acknowledge_issues"]').count()!==1)failures.push('Import lacks explicit unknown acknowledgement');
 console.log(JSON.stringify({failures}));await browser.close();if(failures.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exit(1)});
