const {chromium}=require('C:/Users/咖波/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{
 const context=await browser.newContext({viewport:{width:1366,height:900}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:8768/');
 await page.locator('#password').fill('merchant-test-only');
 await page.locator('#auth-form button').click();
 await page.locator('.merchant-card').first().waitFor({timeout:6000});
 assert.equal(await page.locator('#main').getAttribute('data-view'),'inventory');
 assert.equal(await page.locator('.merchant-card').count(),10);
 assert.equal(await page.locator('.merchant-card button').count(),0,'card is a single clickable control');
 await page.screenshot({path:'.qa/merchant-desktop.png'});
 await page.locator('[data-status="uncounted"]').click();
 await page.waitForFunction(()=>Array.from(document.querySelectorAll('.merchant-card')).every(c=>c.textContent.includes('未盤點')));
 await page.locator('[data-status=""]').click();
 await page.locator('.merchant-card').first().click();
 await page.locator('#dialog[open]').waitFor();
 await page.locator('[data-detail-tab="batches"]').click();
 await page.getByText('進價',{exact:false}).first().waitFor();
 await page.locator('#dialog-close').click();
 await page.locator('[data-inventory-mode="table"]').click();
 await page.locator('[data-count-batch]').first().waitFor();
 const input=page.locator('[data-count-batch]').first(),bid=await input.getAttribute('data-count-batch');
 await input.fill('0');
 await page.locator('[data-action="page"][data-page="2"]').click();
 await page.waitForFunction(()=>document.querySelector('.pager').textContent.includes('2 / 2'));
 await page.locator('[data-count-batch]').first().fill('7');
 await page.locator('[data-action="page"][data-page="1"]').click();
 await page.locator(`[data-count-batch="${bid}"]`).waitFor();
 assert.equal(await page.locator(`[data-count-batch="${bid}"]`).inputValue(),'0');
 await page.locator('[data-inventory-mode="cards"]').click();
 await page.locator('.merchant-card').first().waitFor();
 await page.locator('[data-inventory-mode="table"]').click();
 assert.equal(await page.locator(`[data-count-batch="${bid}"]`).inputValue(),'0');
 await page.setViewportSize({width:1280,height:850});
 await page.waitForTimeout(250);
 assert.equal(await page.locator(`[data-count-batch="${bid}"]`).inputValue(),'0');
 // Simulate a successful save whose response is lost; retry must not duplicate writes.
 const historyBefore=(await (await context.request.get('http://127.0.0.1:8768/api/history?kind=count')).json()).total;
 await page.route('**/api/counts/bulk',async route=>{await route.fetch();await route.abort('failed');},{times:1});
 await page.locator('#save-stocktake').click();
 await page.waitForFunction(()=>document.querySelector('#stocktake-error')?.textContent.includes('已填內容仍保留'));
 assert.equal(await page.locator(`[data-count-batch="${bid}"]`).inputValue(),'0');
 const response=page.waitForResponse(r=>r.url().endsWith('/api/counts/bulk')&&r.request().method()==='POST');
 await page.locator('#save-stocktake').click();
 const saved=await response;assert.equal(saved.status(),200);assert.equal((await saved.json()).results.length,2);
 await page.waitForFunction(()=>document.querySelector('#save-stocktake')?.disabled);
 const historyAfter=(await (await context.request.get('http://127.0.0.1:8768/api/history?kind=count')).json()).total;
 assert.equal(historyAfter-historyBefore,2,'lost-response replay must not duplicate stocktaking');
 assert.equal(await page.locator(`[data-count-batch="${bid}"]`).inputValue(),'');
 await page.screenshot({path:'.qa/merchant-stocktake.png'});
 await page.locator('#settings').click();
 await page.getByRole('button',{name:'匯入原始 Excel',exact:true}).waitFor();
 await page.locator('#dialog-close').click();
 await page.locator('[data-nav="exports"]').click();
 await page.getByRole('heading',{name:'匯出資料',exact:true}).waitFor();
 await page.locator('[data-nav="inventory"]').click();
 await page.locator('[data-inventory-mode="cards"]').click();
 await page.setViewportSize({width:390,height:844});
 await page.waitForTimeout(250);
 await page.locator('.merchant-card').first().waitFor();
 assert(await page.locator('#settings').isVisible(),'mobile settings reachable');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'mobile overflow');
 await page.screenshot({path:'.qa/merchant-mobile.png'});
 assert.deepEqual(errors,[]);console.log('PASS: product landing, cards, filters, detail, draft paging/mode/resize, bulk save, settings, exports, mobile.');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
