CREATE TABLE IF NOT EXISTS line_chats(
 chat TEXT PRIMARY KEY, last_on TEXT NOT NULL, last_at TEXT NOT NULL, message_count BIGINT NOT NULL,
 tail TEXT NOT NULL, menu TEXT, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS line_imports(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 chat TEXT NOT NULL, filename TEXT NOT NULL, created_at TEXT NOT NULL, actor TEXT NOT NULL,
 total_messages BIGINT NOT NULL, new_messages BIGINT NOT NULL, customer_messages BIGINT NOT NULL,
 missing_messages BIGINT NOT NULL DEFAULT 0,
 status TEXT NOT NULL CHECK(status IN ('baseline','empty','pending','converting','done','failed')),
 error TEXT, model TEXT, usage TEXT, cost TEXT, started_at TEXT, converted_at TEXT);
CREATE TABLE IF NOT EXISTS line_messages(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 import_id BIGINT NOT NULL REFERENCES line_imports(id) DEFERRABLE INITIALLY IMMEDIATE,
 sent_on TEXT NOT NULL, sent_at TEXT NOT NULL,
 kind TEXT NOT NULL CHECK(kind IN ('customer','staff','image','recall','other')), raw TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS line_messages_import ON line_messages(import_id, id);
CREATE TABLE IF NOT EXISTS line_orders(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 import_id BIGINT NOT NULL REFERENCES line_imports(id) DEFERRABLE INITIALLY IMMEDIATE,
 sent_on TEXT NOT NULL, sent_at TEXT NOT NULL, customer TEXT NOT NULL, location TEXT NOT NULL,
 action TEXT NOT NULL, carrier TEXT NOT NULL, payment TEXT NOT NULL, note TEXT NOT NULL,
 needs_review BIGINT NOT NULL CHECK(needs_review IN (0,1)), review_reason TEXT NOT NULL,
 status TEXT NOT NULL CHECK(status IN ('open','done','dismissed')), source_ids TEXT NOT NULL,
 created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version BIGINT NOT NULL DEFAULT 1);
CREATE INDEX IF NOT EXISTS line_orders_status ON line_orders(status, sent_on, sent_at);
CREATE TABLE IF NOT EXISTS line_order_items(
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id BIGINT NOT NULL REFERENCES line_orders(id) DEFERRABLE INITIALLY IMMEDIATE,
 name TEXT NOT NULL, product_id BIGINT REFERENCES products(id) DEFERRABLE INITIALLY IMMEDIATE,
 quantity TEXT, unit TEXT NOT NULL, unit_price TEXT, processing TEXT NOT NULL, note TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS line_order_items_order ON line_order_items(order_id, id);
